const router = require("express").Router();
const multer = require("multer");
const path = require("path");
const { authenticate, authorize } = require("../middleware/auth");
const { assignmentController: c } = require("../controllers/session.controller");
const storage = multer.diskStorage({ destination: (req, file, cb) => cb(null, "uploads/"), filename: (req, file, cb) => { const safe = file.originalname.replace(/[^a-zA-Z0-9._-]/g, "_"); cb(null, `${Date.now()}-${safe}`); } });
const upload = multer({ storage, limits: { fileSize: 25 * 1024 * 1024 } });
router.post("/", authenticate, authorize("TUTOR"), upload.single("file"), c.createAssignment);
router.get("/tutor/submissions", authenticate, authorize("TUTOR"), c.getTutorSubmissions);
router.get("/batch/:batchId", authenticate, c.getBatchAssignments);
router.post("/:id/submit", authenticate, authorize("STUDENT"), upload.single("file"), c.submitAssignment);
router.patch("/submissions/:id/review", authenticate, authorize("TUTOR"), c.reviewSubmission);
module.exports = router;
