import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import AppShell from "../../components/layout/AppShell.jsx";
import { PageWrapper } from "../../components/ui/index.jsx";
import { Plus, Users, BookOpen, Calendar, Clock, X, ChevronRight, RefreshCw } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { batchApi, tutorApi } from "../../services/api.js";

function buildBatchName(courseName, startDate) {
  if (!courseName || !startDate) return "";
  const d = new Date(startDate);
  return `${courseName} - ${d.getDate()} ${d.toLocaleString("en-IN", { month: "long" })} ${String(d.getFullYear()).slice(2)}`;
}
function to12Hour(time24) { if (!time24) return ""; const [h,m]=time24.split(":").map(Number); const p=h>=12?"PM":"AM"; return `${h%12||12}:${String(m).padStart(2,"0")} ${p}`; }
function makeSlot(start,end){ return start&&end ? `${to12Hour(start)} – ${to12Hour(end)}` : ""; }
function statusOf(b){ if(b.status==="PENDING_APPROVAL")return"PENDING_APPROVAL"; const n=new Date(),s=b.start_date?new Date(b.start_date):null,e=b.end_date?new Date(b.end_date):null; if(s&&e){if(n<s)return"UPCOMING"; if(n>e)return"COMPLETED"; return"ACTIVE";} return b.status||"UPCOMING"; }

function NewBatchModal({isOpen,onClose,onCreated}){
  const [courses,setCourses]=useState([]); const [loading,setLoading]=useState(false); const [err,setErr]=useState("");
  const [form,setForm]=useState({course_id:"",start_date:"",max_students:50,start_time:"",end_time:"",alt_days:false,sunday_off:true});
  useEffect(()=>{ if(isOpen) tutorApi.approvedCourses().then(r=>{ const list=r.data||[]; setCourses(list); if(list.length===1) setForm(f=>({...f,course_id:list[0].id})); }).catch(e=>{setErr(e.message||"Failed to load approved courses"); setCourses([])}); },[isOpen]);
  const set=(k,v)=>setForm(f=>({...f,[k]:v})); const course=courses.find(c=>c.id===form.course_id); const slot=makeSlot(form.start_time,form.end_time); const batchName=buildBatchName(course?.name,form.start_date);
  const submit=async()=>{ setErr(""); if(!form.course_id)return setErr("No approved course found for your tutor account."); if(!form.start_date)return setErr("Select start date."); if(!form.start_time||!form.end_time)return setErr("Select start and end time."); if(form.start_time>=form.end_time)return setErr("End time must be later than start time."); setLoading(true); try{ const r=await batchApi.create({course_id:form.course_id,start_date:form.start_date,max_students:Number(form.max_students)||50,time_slots:[slot],alt_days:form.alt_days,sunday_off:form.sunday_off}); onCreated(r.data); onClose(); setForm({course_id:courses.length===1?courses[0].id:"",start_date:"",max_students:50,start_time:"",end_time:"",alt_days:false,sunday_off:true}); }catch(e){setErr(e.message||"Failed to create batch.")}finally{setLoading(false)}};
  if(!isOpen)return null;
  return <div className="fixed inset-0 z-50 flex items-center justify-center p-4"><motion.div className="absolute inset-0 bg-black/50 backdrop-blur-sm" initial={{opacity:0}} animate={{opacity:1}} onClick={onClose}/><motion.div className="relative bg-white rounded-2xl shadow-2xl w-full max-w-lg z-10 max-h-[92vh] flex flex-col" initial={{opacity:0,scale:.95,y:20}} animate={{opacity:1,scale:1,y:0}}>
    <div className="px-6 py-5 border-b border-gray-100 flex justify-between"><div><h2 className="text-lg font-extrabold text-dct-dark">Create New Batch</h2><p className="text-xs text-dct-lightgray">Only your approved course is shown</p></div><button onClick={onClose}><X size={18}/></button></div>
    <div className="flex-1 overflow-y-auto px-6 py-5 space-y-5">
      <div><label className="block text-xs font-bold text-dct-gray mb-1.5 uppercase">Approved Course *</label><select className="dct-input" value={form.course_id} onChange={e=>set("course_id",e.target.value)} disabled={courses.length<=1}><option value="">{courses.length?"Select course":"Loading approved course..."}</option>{courses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>{courses.length===0&&!err&&<p className="text-xs text-orange-600 mt-2">No approved course found. Ask admin to approve your tutor application first.</p>}</div>
      <div><label className="block text-xs font-bold text-dct-gray mb-1.5 uppercase">Start Date *</label><input type="date" min={new Date().toISOString().split("T")[0]} className="dct-input" value={form.start_date} onChange={e=>set("start_date",e.target.value)}/></div>
      {batchName&&<div className="rounded-xl p-4 border border-blue-200 bg-blue-50"><p className="text-[10px] font-bold uppercase text-blue-400">Batch name</p><p className="text-sm font-bold text-dct-dark">{batchName}</p></div>}
      <div><label className="block text-xs font-bold text-dct-gray mb-2 uppercase">Class Timing *</label><div className="grid grid-cols-2 gap-3"><input type="time" className="dct-input" value={form.start_time} onChange={e=>set("start_time",e.target.value)}/><input type="time" className="dct-input" value={form.end_time} onChange={e=>set("end_time",e.target.value)}/></div>{slot&&<span className="mt-3 inline-flex items-center gap-2 text-xs font-bold px-3 py-2 rounded-full border border-blue-200 bg-blue-50 text-dct-primary"><Clock size={12}/>{slot}</span>}</div>
      <div className="grid grid-cols-2 gap-3"><button type="button" onClick={()=>set("alt_days",!form.alt_days)} className={`p-3 rounded-xl border-2 text-left ${form.alt_days?"border-dct-primary bg-blue-50":"border-gray-200"}`}><p className="text-xs font-bold">Alternate Days</p><p className="text-[10px] text-dct-lightgray">Every 2 days</p></button><button type="button" onClick={()=>set("sunday_off",!form.sunday_off)} className={`p-3 rounded-xl border-2 text-left ${form.sunday_off?"border-dct-primary bg-blue-50":"border-gray-200"}`}><p className="text-xs font-bold">Sunday Off</p><p className="text-[10px] text-dct-lightgray">Skip Sundays</p></button></div>
      <div><label className="block text-xs font-bold text-dct-gray mb-1.5 uppercase">Max Students</label><input type="number" min="1" max="200" className="dct-input" value={form.max_students} onChange={e=>set("max_students",e.target.value)}/></div>
      {err&&<div className="bg-red-50 border border-red-200 rounded-xl px-4 py-3 text-red-600 text-sm text-center">{err}</div>}
    </div><div className="px-6 py-4 border-t"><button onClick={submit} disabled={loading||courses.length===0} className="w-full py-3.5 rounded-xl text-white text-sm font-bold disabled:opacity-60 bg-dct-primary">{loading?"Creating...":"Submit for Admin Approval →"}</button></div></motion.div></div>;
}

function BatchCard({batch,index}){ const nav=useNavigate(); const st=statusOf(batch); const slots=batch.time_slots||[]; const enrolled=batch._count?.enrollments||0; const sessions=batch._count?.scheduled_sessions||0; const pct=Math.round(enrolled/(batch.max_students||1)*100); const map={PENDING_APPROVAL:["Pending Approval","bg-yellow-50 text-yellow-700 border-yellow-200"],UPCOMING:["Upcoming","bg-blue-50 text-blue-700 border-blue-200"],ACTIVE:["Active","bg-green-50 text-green-700 border-green-200"],COMPLETED:["Completed","bg-gray-50 text-gray-600 border-gray-200"]}; const [label,cls]=map[st]||[st,"bg-gray-50 text-gray-600 border-gray-200"];
  return <motion.div onClick={()=>nav(`/tutor/batches/${batch.id}/sessions`)} className="bg-white rounded-2xl border border-gray-100 p-5 cursor-pointer hover:shadow-lg hover:border-dct-primary/30 transition-all" style={{boxShadow:"0 2px 12px rgba(0,0,0,.05)"}} initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:index*.05}} whileHover={{y:-3}}>
    <div className="flex items-start justify-between mb-3"><span className={`text-xs font-bold px-3 py-1 rounded-full border ${cls}`}>{label}</span><span className="text-[10px] text-dct-lightgray">{new Date(batch.created_at||Date.now()).toLocaleDateString("en-IN")}</span></div><h3 className="font-extrabold text-dct-dark text-sm mb-0.5 leading-snug">{batch.name}</h3><p className="text-xs text-dct-lightgray mb-3">{batch.course?.name}</p>
    {slots.length>0&&<div className="flex flex-wrap gap-1.5 mb-3">{slots.map(s=><span key={s} className="flex items-center gap-1 text-[10px] font-semibold px-2 py-1 rounded-full bg-blue-50 text-dct-primary"><Clock size={9}/>{s}</span>)}</div>}
    <div className="grid grid-cols-2 gap-2 mb-3"><div className="border rounded-lg p-2.5"><p className="text-xs font-bold">{batch.start_date?new Date(batch.start_date).toLocaleDateString("en-IN"):"—"}</p><p className="text-[10px] text-dct-lightgray">Start</p></div><div className="border rounded-lg p-2.5"><p className="text-xs font-bold">{batch.end_date?new Date(batch.end_date).toLocaleDateString("en-IN"):"—"}</p><p className="text-[10px] text-dct-lightgray">End</p></div></div>
    <div className="flex items-center gap-4 text-xs text-dct-gray mb-3"><span className="flex items-center gap-1"><Users size={11}/>{enrolled}/{batch.max_students}</span><span className="flex items-center gap-1"><BookOpen size={11}/>{sessions} sessions</span></div><div className="h-1.5 bg-gray-100 rounded-full overflow-hidden mb-4"><div className="h-full bg-dct-primary" style={{width:`${pct}%`}}/></div><div className="flex items-center justify-between pt-3 border-t"><span className="text-xs font-bold text-dct-primary">Open Sessions</span><ChevronRight size={16} className="text-dct-primary"/></div>
  </motion.div>; }

export default function MyBatches(){ const [batches,setBatches]=useState([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[filter,setFilter]=useState("ALL"); const load=()=>{setLoading(true); batchApi.mine().then(r=>setBatches(r.data||[])).catch(console.error).finally(()=>setLoading(false))}; useEffect(load,[]); const list=filter==="ALL"?batches:batches.filter(b=>statusOf(b)===filter);
 return <AppShell><PageWrapper><div className="flex items-center justify-between mb-6 gap-3 flex-wrap"><div><h1 className="text-2xl font-extrabold text-dct-dark">My Batches</h1><p className="text-sm text-dct-gray">{batches.length} total</p></div><div className="flex gap-2"><button onClick={load} className="flex items-center gap-2 px-4 py-2.5 rounded-xl border bg-white text-sm font-bold"><RefreshCw size={15} className={loading?"animate-spin":""}/>Refresh</button><button onClick={()=>setOpen(true)} className="flex items-center gap-2 px-5 py-2.5 rounded-xl text-white text-sm font-bold bg-dct-primary"><Plus size={16}/>New Batch</button></div></div><div className="flex gap-2 mb-6 flex-wrap">{[["ALL","All"],["PENDING_APPROVAL","Pending"],["UPCOMING","Upcoming"],["ACTIVE","Active"],["COMPLETED","Completed"]].map(([k,l])=><button key={k} onClick={()=>setFilter(k)} className={`px-4 py-2 rounded-xl text-xs font-semibold ${filter===k?"bg-dct-primary text-white":"bg-gray-100 text-dct-gray"}`}>{l}</button>)}</div>{loading&&<div className="text-center py-16 text-dct-gray text-sm">Loading...</div>}{!loading&&list.length===0&&<div className="bg-white rounded-2xl p-16 text-center border"><Calendar size={40} className="mx-auto mb-3 text-gray-300"/><p className="font-bold">No batches</p></div>}<div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-4">{list.map((b,i)=><BatchCard key={b.id} batch={b} index={i}/>)}</div><AnimatePresence>{open&&<NewBatchModal isOpen={open} onClose={()=>setOpen(false)} onCreated={b=>setBatches(x=>[b,...x])}/>}</AnimatePresence></PageWrapper></AppShell>}
