import CoursePage from "./CoursePage.jsx";

const COURSE = {
  slug: "analysis-with-ansys",
  name: "Analysis With Ansys",
  tagline: "Build FEA/CAE Confidence Like 2–3 Years Experience",
  heroCopy: "Practical ANSYS Workbench training covering FEA fundamentals, meshing, static structural, contact, modal, thermal, convergence thinking and professional CAE reports.",
  eyebrow: "CAE / FEA Career Program",
  badge: "⚙️ CAE Career Track",
  badgeBg: "#037EC4",
  badgeColor: "#fff",
  price: 22000,
  slashPrice: 30000,
  rating: "4.8",
  reviews: "180+",
  enrolled: "180+",
  duration: "4 Months",
  sessions: "85",
  projectCount: "10",
  tools: ["ANSYS Workbench", "Static Structural", "Meshing", "Modal", "Thermal", "CAE Reports"],
  packageRange: "₹4–9 LPA",
  trustYears: "7+",
  partnerLine: "Digital CAD Training is partner and authorized by CADPOINT for professional CAD training direction.",
  trustCopy: "Students see the complete syllabus, project roadmap, career path and registration value clearly before joining. The program is structured for 2–3 years experience-level practical confidence.",
  packageNote: "Package depends on skill, location, interview performance and company requirement. We guide students with portfolio, resume direction, mock interview preparation and PAN India job updates.",
  trustHighlights: ["CADPOINT Authorized Partner", "PAN India MNC/OEM hiring exposure", "2–3 years experience-level learning", "Package guidance ₹4–9 LPA"],
  trustProofs: [
    { title: "Industry-level practical workflow", text: "Every module is connected with real company work, design checks, reports and interview explanation." },
    { title: "Portfolio-first learning", text: "Students build project proof instead of only watching software commands." },
    { title: "Placement-focused mentoring", text: "Resume, portfolio, mock interview and job-sharing support are connected with the course journey." },
    { title: "Mobile-friendly clarity", text: "Syllabus, projects, demo and batch information are visible clearly before registration." },
  ],
  tutor: { name: "Balkrishna Dhuri", exp: "12+ Years Experience", companies: "Automotive Engineering Expert", initial: "B" },
  outcomes: [
    "Understand complete CAE workflow from CAD cleanup to professional result report",
    "Create reliable mesh with quality checks, convergence thinking and realistic assumptions",
    "Apply loads, constraints, contacts and material properties for practical component analysis",
    "Interpret stress, deformation, safety factor, modal and thermal-stress results confidently",
    "Prepare professional CAE reports with assumptions, setup screenshots and conclusions",
    "Build automotive-style CAE portfolio projects for analysis engineer interviews"
  ],
  includes: [
    { icon: "📹", label: "85-session roadmap", sub: "Live sessions + lifetime recordings" },
    { icon: "🏭", label: "10 portfolio projects", sub: "Industry workflow and interview explanation" },
    { icon: "📊", label: "Project documentation", sub: "Reports, review points and portfolio proof" },
    { icon: "💼", label: "Placement support", sub: "Resume, portfolio and mock interview prep" },
    { icon: "❓", label: "Doubt support", sub: "Project correction and guidance" },
    { icon: "♾", label: "Lifetime access", sub: "Recordings for revision anytime" }
  ],
  syllabusSessions: [
    { no: 1, title: "FEA and CAE engineer role", trainer: "Analysis With Ansys", category: "Fundamentals" },
    { no: 2, title: "Stress, strain, deformation and factor of safety", trainer: "Analysis With Ansys", category: "Fundamentals" },
    { no: 3, title: "ANSYS Workbench interface and project schematic", trainer: "Analysis With Ansys", category: "Fundamentals" },
    { no: 4, title: "Units, coordinate systems and result accuracy", trainer: "Analysis With Ansys", category: "Fundamentals" },
    { no: 5, title: "CAD import, cleanup and geometry simplification", trainer: "Analysis With Ansys", category: "Fundamentals" },
    { no: 6, title: "Material properties and engineering assumptions", trainer: "Analysis With Ansys", category: "Fundamentals" },
    { no: 7, title: "Element types and mesh fundamentals", trainer: "Analysis With Ansys", category: "Fundamentals" },
    { no: 8, title: "Mesh controls, sizing and local refinement", trainer: "Analysis With Ansys", category: "CAD Workflow" },
    { no: 9, title: "Element quality: skewness, aspect ratio and Jacobian", trainer: "Analysis With Ansys", category: "CAD Workflow" },
    { no: 10, title: "Named selections and contact preparation", trainer: "Analysis With Ansys", category: "CAD Workflow" },
    { no: 11, title: "Boundary conditions and realistic constraints", trainer: "Analysis With Ansys", category: "CAD Workflow" },
    { no: 12, title: "Force, pressure, bearing load and remote load setup", trainer: "Analysis With Ansys", category: "CAD Workflow" },
    { no: 13, title: "Linear static structural workflow", trainer: "Analysis With Ansys", category: "CAD Workflow" },
    { no: 14, title: "Equivalent stress and deformation interpretation", trainer: "Analysis With Ansys", category: "CAD Workflow" },
    { no: 15, title: "Principal stress, strain and safety factor review", trainer: "Analysis With Ansys", category: "CAD Workflow" },
    { no: 16, title: "Bracket static analysis setup", trainer: "Analysis With Ansys", category: "Design Rules" },
    { no: 17, title: "Mounting lug and bolt hole stress study", trainer: "Analysis With Ansys", category: "Design Rules" },
    { no: 18, title: "Contact definition: bonded, frictionless and no separation", trainer: "Analysis With Ansys", category: "Design Rules" },
    { no: 19, title: "Assembly contact analysis workflow", trainer: "Analysis With Ansys", category: "Design Rules" },
    { no: 20, title: "Bolt pretension and fastener basics", trainer: "Analysis With Ansys", category: "Design Rules" },
    { no: 21, title: "Mesh independence and convergence study", trainer: "Analysis With Ansys", category: "Design Rules" },
    { no: 22, title: "Result validation and common CAE mistakes", trainer: "Analysis With Ansys", category: "Design Rules" },
    { no: 23, title: "Design improvement loop from CAE results", trainer: "Analysis With Ansys", category: "Design Rules" },
    { no: 24, title: "Report format: assumptions, loads and results", trainer: "Analysis With Ansys", category: "Manufacturing" },
    { no: 25, title: "Modal analysis theory and natural frequency", trainer: "Analysis With Ansys", category: "Manufacturing" },
    { no: 26, title: "Modal setup and mode shape interpretation", trainer: "Analysis With Ansys", category: "Manufacturing" },
    { no: 27, title: "Frequency risk and design improvement logic", trainer: "Analysis With Ansys", category: "Manufacturing" },
    { no: 28, title: "Thermal analysis basics and boundary conditions", trainer: "Analysis With Ansys", category: "Manufacturing" },
    { no: 29, title: "Thermal stress coupling fundamentals", trainer: "Analysis With Ansys", category: "Manufacturing" },
    { no: 30, title: "Buckling analysis for thin components", trainer: "Analysis With Ansys", category: "Manufacturing" },
    { no: 31, title: "Fatigue overview and durability thinking", trainer: "Analysis With Ansys", category: "Manufacturing" },
    { no: 32, title: "Plastic part stiffness and clip load case", trainer: "Analysis With Ansys", category: "Validation" },
    { no: 33, title: "Sheet metal stiffness and reinforcement study", trainer: "Analysis With Ansys", category: "Validation" },
    { no: 34, title: "Control arm load case and support logic", trainer: "Analysis With Ansys", category: "Validation" },
    { no: 35, title: "Engine mount static and modal study", trainer: "Analysis With Ansys", category: "Validation" },
    { no: 36, title: "Seat frame load path and deformation study", trainer: "Analysis With Ansys", category: "Validation" },
    { no: 37, title: "Alloy wheel radial load analysis basics", trainer: "Analysis With Ansys", category: "Validation" },
    { no: 38, title: "Pressure vessel analysis and code thinking", trainer: "Analysis With Ansys", category: "Validation" },
    { no: 39, title: "Nonlinear basics and large deformation overview", trainer: "Analysis With Ansys", category: "Validation" },
    { no: 40, title: "Frictional contact and convergence troubleshooting", trainer: "Analysis With Ansys", category: "Documentation" },
    { no: 41, title: "Solver errors, warnings and debugging workflow", trainer: "Analysis With Ansys", category: "Documentation" },
    { no: 42, title: "CAE result screenshots and presentation", trainer: "Analysis With Ansys", category: "Documentation" },
    { no: 43, title: "Final CAE report project preparation", trainer: "Analysis With Ansys", category: "Documentation" },
    { no: 44, title: "CAE interview questions and explanation practice", trainer: "Analysis With Ansys", category: "Documentation" },
    { no: 45, title: "Final technical mock review for analysis role", trainer: "Analysis With Ansys", category: "Documentation" },
    { no: 46, title: "Automotive CAE portfolio packaging", trainer: "Analysis With Ansys", category: "Documentation" },
    { no: 47, title: "Client review style CAE presentation", trainer: "Analysis With Ansys", category: "Documentation" },
    { no: 48, title: "Final project validation and feedback", trainer: "Analysis With Ansys", category: "Interview" },
    { no: 49, title: "Resume points for CAE engineer profile", trainer: "Analysis With Ansys", category: "Interview" },
    { no: 50, title: "Final CAE career roadmap", trainer: "Analysis With Ansys", category: "Interview" }
  ],
  projectLibrary: ["Engine Mount Analysis", "Control Arm Analysis", "Chassis Bracket Analysis", "Door Hinge Contact Analysis", "Pressure Vessel Analysis", "Alloy Wheel Analysis", "Seat Frame Analysis", "Plastic Clip Load Analysis", "Thermal Stress Case Study", "Final CAE Report Project"],
  portfolioProjects: [
    {
      no: 1,
      title: "Engine Mount Analysis",
      area: "Static + Modal",
      desc: "Stress, deformation and modal behavior of automotive mounting component.",
      frontImage: "/images/projects/ansys-engine-mount-cad.svg",
      backImage: "/images/projects/ansys-engine-mount-ref.svg",
    },
    {
      no: 2,
      title: "Control Arm Analysis",
      area: "Suspension CAE",
      desc: "Load case setup, support definition and stress interpretation.",
      frontImage: "/images/projects/ansys-control-arm-cad.svg",
      backImage: "/images/projects/ansys-control-arm-ref.svg",
    },
    {
      no: 3,
      title: "Chassis Bracket Analysis",
      area: "Static Structural",
      desc: "Bracket strength, factor of safety and design improvement loop.",
      frontImage: "/images/projects/ansys-chassis-bracket-cad.svg",
      backImage: "/images/projects/ansys-chassis-bracket-ref.svg",
    },
    {
      no: 4,
      title: "Door Hinge Contact Analysis",
      area: "Contact Analysis",
      desc: "Assembly contacts, bolt region and hinge load transfer study.",
      frontImage: "/images/projects/ansys-door-hinge-cad.svg",
      backImage: "/images/projects/ansys-door-hinge-ref.svg",
    },
    {
      no: 5,
      title: "Pressure Vessel Analysis",
      area: "Industrial CAE",
      desc: "Pressure loading, stress review and result validation workflow.",
      frontImage: "/images/projects/ansys-pressure-vessel-cad.svg",
      backImage: "/images/projects/ansys-pressure-vessel-ref.svg",
    },
    {
      no: 6,
      title: "Alloy Wheel Analysis",
      area: "Automotive CAE",
      desc: "Radial load case, deformation and safety factor interpretation.",
      frontImage: "/images/projects/ansys-alloy-wheel-cad.svg",
      backImage: "/images/projects/ansys-alloy-wheel-ref.svg",
    },
    {
      no: 7,
      title: "Seat Frame Analysis",
      area: "Frame Analysis",
      desc: "Seat structure load path, stiffness and deformation study.",
      frontImage: "/images/projects/ansys-seat-frame-cad.svg",
      backImage: "/images/projects/ansys-seat-frame-ref.svg",
    },
    {
      no: 8,
      title: "Plastic Clip Load Analysis",
      area: "Plastic Component",
      desc: "Plastic trim clip load case and deformation validation.",
      frontImage: "/images/projects/ansys-plastic-clip-cad.svg",
      backImage: "/images/projects/ansys-plastic-clip-ref.svg",
    },
    {
      no: 9,
      title: "Thermal Stress Case Study",
      area: "Thermal CAE",
      desc: "Temperature boundary conditions and coupled thermal-stress result review.",
      frontImage: "/images/projects/ansys-thermal-stress-cad.svg",
      backImage: "/images/projects/ansys-thermal-stress-ref.svg",
    },
    {
      no: 10,
      title: "Final CAE Report Project",
      area: "Portfolio Report",
      desc: "Complete CAE workflow with assumptions, setup, results and conclusion.",
      frontImage: "/images/projects/ansys-final-report-cad.svg",
      backImage: "/images/projects/ansys-final-report-ref.svg",
    }
  ],
  courseFaqs: [
    { q: "Do I need prior experience?", a: "No. The course starts from fundamentals and builds toward practical industry-level projects." },
    { q: "Are sessions live or recorded?", a: "Sessions are live on Zoom and recordings are available for lifetime revision." },
    { q: "Will I build portfolio projects?", a: "Yes. The course includes structured projects that students can explain in interviews." },
    { q: "Will this help in interviews?", a: "Yes. Topics are mapped to real workflow, design decisions, reports and interview questions." },
    { q: "Can freshers join?", a: "Yes. Diploma and BE mechanical freshers can join if they are serious about design/CAE/tooling career." },
    { q: "Is placement support included?", a: "Yes. Resume, portfolio, mock interview and job-sharing support are included." }
  ],
  placements: ["Tata Technologies", "Tata Motors", "Mahindra & Mahindra", "Maruti Suzuki", "Hyundai Motors", "Mercedes-Benz R&D", "BMW Group India", "Volkswagen Group", "Skoda Auto Volkswagen", "Stellantis", "Renault Nissan", "Ashok Leyland", "Magna", "Forvia", "Motherson", "Bosch", "Continental", "ZF", "Valeo", "Aptiv", "Denso", "Schaeffler", "Lear Corporation", "Adient", "Visteon", "Capgemini Engineering", "L&T Technology Services", "KPIT", "Tata Elxsi", "HCLTech", "Wipro", "Tech Mahindra", "Quest Global", "Segula Technologies", "EDAG", "Neilsoft", "Caresoft Global", "Hinduja Tech", "Bajaj Auto", "TVS Motor", "Hero MotoCorp", "Ather Energy", "Ola Electric", "Uno Minda", "Varroc", "Lumax", "Faurecia", "Plastic Omnium", "Yanfeng", "Force Motors"],
};

export default function AnalysisWithAnsysPage() {
  return <CoursePage course={COURSE} />;
}
