import CoursePage from "./CoursePage.jsx";

const COURSE = {
  slug: "analysis-with-ansys",
  name: "Analysis With Ansys",
  tagline: "Build FEA/CAE Confidence Like 2–3 Years Experience",
  badge: "⚙️ CAE Career Track",
  badgeBg: "#037EC4",
  badgeColor: "#fff",
  price: 22000,
  slashPrice: 30000,
  rating: "4.8",
  reviews: "156",
  enrolled: "156+",
  duration: "4 Months",
  sessions: "45+",
  projectCount: "10",
  tools: ["ANSYS Workbench", "Static Structural", "Meshing", "Modal", "Thermal", "CAE Reports"],
  packageRange: "₹4–9 LPA",
  trustYears: "7+",
  partnerLine: "Digital CAD Training is partner and authorized by CADPOINT for professional CAD training direction.",
  trustCopy: "Students see the complete syllabus, projects, career path and registration value clearly before joining. The program is positioned around CADPOINT authorization, PAN India MNC/OEM/Tier-1 hiring exposure and placement-focused mentoring.",
  packageNote: "Package depends on skill, location, interview performance and company requirement. We guide students for fresher to junior CAE / analysis engineer level roles across PAN India CAE and automotive engineering hiring networks.",
  trustHighlights: ["CADPOINT Authorized Partner", "PAN India MNC/OEM hiring exposure", "7+ years trust connection", "Package guidance ₹4–9 LPA"],
  trustProofs: [
    { title: "CADPOINT authorized partner", text: "Adds credibility that the training brand is connected with a professional CAD education ecosystem." },
    { title: "PAN India hiring exposure", text: "Students are prepared for MNC, OEM and Tier-1 supplier interviews across multiple automotive locations." },
    { title: "2–3 years experience-level learning", text: "Projects, reports, design decisions and interview preparation are structured beyond basic tool commands." },
    { title: "Placement-focused mentoring", text: "Resume, portfolio, mock interview and job-sharing support are connected with the course journey." },
  ],
  tutor: { name: "Balkrishna Dhuri", exp: "12+ Years Experience", companies: "Automotive Product Design Expert", initial: "B" },
  outcomes: [
    "Understand complete CAE workflow from CAD cleanup to final report",
    "Create reliable mesh with element quality checks and convergence thinking",
    "Apply realistic loads, constraints, contacts and material properties",
    "Interpret stress, deformation, factor of safety and modal results",
    "Prepare professional CAE reports for interview and project discussion",
    "Handle automotive component-level analysis like an industry engineer",
  ],
  includes: [
    { icon: "📹", label: "45+ Live Sessions", sub: "Recordings + practice support" },
    { icon: "🧪", label: "10 CAE Projects", sub: "Automotive-style analysis cases" },
    { icon: "📊", label: "Report Training", sub: "Result interpretation + documentation" },
    { icon: "💼", label: "Career Support", sub: "Resume + interview preparation" },
    { icon: "❓", label: "Doubt Support", sub: "Case-by-case solver guidance" },
    { icon: "♾", label: "Lifetime Access", sub: "All recordings forever" },
  ],
  syllabus: [
    { phase: "Phase 1 — CAE Foundation", sessions: "Sessions 01–08", topics: ["FEA fundamentals and CAE engineer role", "Stress, strain, deformation, safety factor", "ANSYS Workbench interface and project workflow", "CAD cleanup and geometry simplification", "Material properties and engineering assumptions", "Units, coordinate systems and result accuracy"] },
    { phase: "Phase 2 — Meshing & Preprocessing", sessions: "Sessions 09–18", topics: ["Mesh controls and element types", "Element quality, skewness, aspect ratio and Jacobian", "Local mesh refinement near fillets, holes and contacts", "Named selections and contact regions", "Boundary conditions and realistic load application", "Mesh independence / convergence study"] },
    { phase: "Phase 3 — Static Structural Analysis", sessions: "Sessions 19–29", topics: ["Linear static structural setup", "Bolted bracket and mounting analysis", "Contact definition: bonded, frictionless and no-separation", "Remote force, bearing load and bolt pretension basics", "Equivalent stress, principal stress and deformation review", "Factor of safety and design improvement loop"] },
    { phase: "Phase 4 — Advanced CAE Workflows", sessions: "Sessions 30–39", topics: ["Nonlinear basics and large deformation", "Modal analysis and natural frequency interpretation", "Thermal analysis and coupled thermal-stress basics", "Buckling analysis for thin components", "Fatigue overview and durability thinking", "Result validation and common CAE mistakes"] },
    { phase: "Phase 5 — Industry Projects & Portfolio", sessions: "Sessions 40–45+", topics: ["Automotive bracket structural analysis", "Plastic component load case analysis", "Sheet metal part stiffness analysis", "Assembly contact analysis", "Professional CAE report creation", "Interview questions and portfolio explanation"] },
  ],
  projects: [
    { name: "Automotive Mounting Bracket Static Analysis", type: "LIVE", difficulty: "Advanced" },
    { name: "Door Hinge Bracket Contact Analysis", type: "LIVE", difficulty: "Advanced" },
    { name: "Plastic Trim Clip Load Analysis", type: "LIVE", difficulty: "Intermediate" },
    { name: "Sheet Metal Stiffness Analysis", type: "Practice", difficulty: "Intermediate" },
    { name: "Modal Analysis of Automotive Component", type: "Practice", difficulty: "Intermediate" },
    { name: "Thermal Stress Case Study", type: "Practice", difficulty: "Advanced" },
    { name: "Buckling Study for Thin Structure", type: "Practice", difficulty: "Advanced" },
    { name: "Mesh Convergence Study", type: "Practice", difficulty: "Intermediate" },
    { name: "Assembly Contact Validation", type: "Practice", difficulty: "Advanced" },
    { name: "Final CAE Report Portfolio Project", type: "Portfolio", difficulty: "Advanced" },
  ],
  faqs: [
    { q: "Do I need prior CAE experience?", a: "No. The course starts from FEA fundamentals and builds up to automotive-style component analysis and report preparation." },
    { q: "Which software will be used?", a: "ANSYS Workbench with focus on Static Structural, Meshing, Modal, Thermal and result interpretation." },
    { q: "Is this useful for design engineers?", a: "Yes. Product designers who understand analysis can make stronger design decisions and discuss validation confidently." },
    { q: "Will I create reports?", a: "Yes. Report creation, result screenshots, assumptions, boundary conditions and conclusion writing are included." },
    { q: "Will this help in interviews?", a: "Yes. The syllabus is designed around practical CAE workflow and technical interview discussion points." },
    { q: "Can I pay in EMI?", a: "Yes. Contact Digital CAD Training for current EMI options and batch details." },
  ],
  placements: ["TATA ELXSI", "Capgemini", "Wipro", "L&T", "SEGULA", "Mahindra", "TATA Technologies", "HCL"],
};

export default function AnalysisWithAnsysPage() {
  return <CoursePage course={COURSE} />;
}
