import CoursePage from "./CoursePage.jsx";

const COURSE = {
  slug: "mould-design",
  name: "Mould Design",
  tagline: "Injection Mould Design Training With Toolroom-Level Workflow",
  badge: "🏭 Tooling Specialist",
  badgeBg: "#FFEB3A",
  badgeColor: "#1C1C1C",
  price: 22000,
  slashPrice: 30000,
  rating: "4.8",
  reviews: "142",
  enrolled: "142+",
  duration: "4 Months",
  sessions: "45+",
  projectCount: "12",
  tools: ["CATIA V5", "Mould Tooling", "Core-Cavity", "Runner-Gate", "Cooling", "DFM"],
  packageRange: "₹4–9 LPA",
  trustYears: "7+",
  partnerLine: "Digital CAD Training is partner and authorized by CADPOINT for professional CAD training direction.",
  trustCopy: "Students see the complete syllabus, projects, career path and registration value clearly before joining. The program is positioned around CADPOINT authorization, PAN India MNC/OEM/Tier-1 hiring exposure and placement-focused mentoring.",
  packageNote: "Package depends on skill, location, interview performance and company requirement. We guide students for fresher to junior mould design / tooling engineer level roles across PAN India tooling, mould and automotive supplier hiring networks.",
  trustHighlights: ["CADPOINT Authorized Partner", "PAN India MNC/OEM hiring exposure", "7+ years trust connection", "Package guidance ₹4–9 LPA"],
  trustProofs: [
    { title: "CADPOINT authorized partner", text: "Adds credibility that the training brand is connected with a professional CAD education ecosystem." },
    { title: "PAN India hiring exposure", text: "Students are prepared for MNC, OEM and Tier-1 supplier interviews across multiple automotive locations." },
    { title: "2–3 years experience-level learning", text: "Projects, reports, design decisions and interview preparation are structured beyond basic tool commands." },
    { title: "Placement-focused mentoring", text: "Resume, portfolio, mock interview and job-sharing support are connected with the course journey." },
  ],
  tutor: { name: "Balkrishna Dhuri", exp: "12+ Years Experience", companies: "Automotive Product Design Expert", initial: "B" },
  outcomes: [
    "Understand plastic part feasibility from mould design point of view",
    "Create tooling direction, parting line and core-cavity strategy",
    "Design runner, gate, cooling, ejector and mould-base layouts",
    "Handle slider, lifter, shut-off and undercut related decisions",
    "Read mould flow reports and connect defects with design improvements",
    "Prepare mould design documentation, BOM and review-ready outputs",
  ],
  includes: [
    { icon: "📹", label: "45+ Live Sessions", sub: "Recordings + revision support" },
    { icon: "🧩", label: "12 Tooling Projects", sub: "Plastic part + mould workflow" },
    { icon: "🏭", label: "Toolroom Workflow", sub: "Design review + manufacturing thinking" },
    { icon: "📜", label: "Certificate", sub: "Career-ready course completion" },
    { icon: "❓", label: "Doubt Support", sub: "Practical project correction" },
    { icon: "💼", label: "Placement Support", sub: "Resume + portfolio + referrals" },
  ],
  syllabus: [
    { phase: "Phase 1 — Plastic & Injection Moulding Foundation", sessions: "Sessions 01–08", topics: ["Plastic material basics and shrinkage", "Injection moulding cycle and machine overview", "Plastic part design review from tooling side", "Wall thickness, ribs, bosses, draft and fillets", "Mould feasibility and DFM checklist", "Common defects: sink, warpage, weld line, flow mark"] },
    { phase: "Phase 2 — Tooling Direction & Core-Cavity", sessions: "Sessions 09–18", topics: ["Tooling direction selection methods", "Parting line and parting surface creation", "Core, cavity and insert strategy", "Shut-off surfaces and sealing areas", "Undercut identification and slider/lifter decision", "Draft analysis and manufacturability validation"] },
    { phase: "Phase 3 — Mould Base, Runner, Gate & Cooling", sessions: "Sessions 19–30", topics: ["Mould base selection and layout", "Sprue, runner and gate design basics", "Gate location decision and filling logic", "Cooling channel design and cycle time thinking", "Venting strategy and air trap prevention", "Ejector pin layout and ejection force basics"] },
    { phase: "Phase 4 — Advanced Tooling Mechanisms", sessions: "Sessions 31–39", topics: ["Slider mechanism design", "Lifter mechanism design", "Wear plates, guide pins and locking systems", "Ejector system detailing", "Mould flow report reading", "Design changes based on toolroom feedback"] },
    { phase: "Phase 5 — Industry Projects & Documentation", sessions: "Sessions 40–45+", topics: ["Door trim mould strategy project", "Cup holder core-cavity project", "Bumper bracket mould design project", "2D drawing and BOM preparation", "Mould design review checklist", "Portfolio and interview preparation"] },
  ],
  projects: [
    { name: "Door Trim Core-Cavity Strategy", type: "LIVE", difficulty: "Advanced" },
    { name: "Cup Holder Mould Layout", type: "LIVE", difficulty: "Advanced" },
    { name: "Bumper Bracket Tooling Project", type: "LIVE", difficulty: "Intermediate" },
    { name: "Slider Mechanism Case Study", type: "Practice", difficulty: "Advanced" },
    { name: "Lifter Mechanism Case Study", type: "Practice", difficulty: "Advanced" },
    { name: "Runner and Gate Design Project", type: "Practice", difficulty: "Intermediate" },
    { name: "Cooling Channel Layout Project", type: "Practice", difficulty: "Intermediate" },
    { name: "Ejector System Layout", type: "Practice", difficulty: "Intermediate" },
    { name: "Mould Flow Report Reading", type: "Practice", difficulty: "Advanced" },
    { name: "DFM Checklist Project", type: "Practice", difficulty: "Intermediate" },
    { name: "Toolroom Review Documentation", type: "Portfolio", difficulty: "Advanced" },
    { name: "Final Mould Design Portfolio", type: "Portfolio", difficulty: "Advanced" },
  ],
  faqs: [
    { q: "Do I need product design knowledge first?", a: "Basic plastic part design knowledge is helpful, but the course starts with moulding and tooling fundamentals before advanced mould design." },
    { q: "Which software is used?", a: "CATIA V5 is used for design workflow. The main focus is tooling logic, core-cavity strategy and mould design decisions." },
    { q: "Is this suitable for toolroom or design engineers?", a: "Yes. It is useful for product designers, tooling engineers, diploma/BE mechanical freshers and production/quality engineers switching into design/tooling." },
    { q: "Will mould flow be covered?", a: "Mould flow report reading and design interpretation are included. The focus is how to use reports for design and tooling decisions." },
    { q: "Will I build portfolio projects?", a: "Yes. You will work on multiple mould strategy, core-cavity, runner-gate, cooling and final documentation projects." },
    { q: "Can I pay in EMI?", a: "Yes. Contact Digital CAD Training for current EMI options and batch details." },
  ],
  placements: ["Motherson", "Bright Brothers", "TATA Technologies", "Faurecia", "Mahindra", "SEGULA", "Capgemini", "Wipro"],
};

export default function MouldDesignPage() {
  return <CoursePage course={COURSE} />;
}
