import CoursePage from "./CoursePage.jsx";

const COURSE = {
  slug: "mould-design",
  name: "Mould Design",
  tagline: "Injection Mould Design Training With Toolroom-Level Workflow",
  heroCopy: "Toolroom-level injection mould design training covering mould feasibility, core-cavity, parting, runner-gate, cooling, ejection, slider/lifter logic and portfolio tooling projects.",
  eyebrow: "Injection Mould Design Career Program",
  badge: "🏭 Tooling Specialist",
  badgeBg: "#037EC4",
  badgeColor: "#fff",
  price: 22000,
  slashPrice: 30000,
  rating: "4.8",
  reviews: "180+",
  enrolled: "180+",
  duration: "4 Months",
  sessions: "85",
  projectCount: "10",
  tools: ["CATIA V5", "Core-Cavity", "Runner-Gate", "Cooling", "Slider-Lifter", "DFM"],
  packageRange: "₹4–9 LPA",
  trustYears: "7+",
  partnerLine: "Digital CAD Training is partner and authorized by CADPOINT for professional CAD training direction.",
  trustCopy: "Students see the complete syllabus, project roadmap, career path and registration value clearly before joining. The program is structured for 2–3 years experience-level practical confidence.",
  packageNote: "Package depends on skill, location, interview performance and company requirement. We guide students with portfolio, resume direction, mock interview preparation and PAN India job updates.",
  trustHighlights: ["CADPOINT Authorized Partner", "PAN India MNC/OEM hiring exposure", "2–3 years experience-level learning", "Package guidance ₹4–9 LPA"],
  trustProofs: [
    { title: "Industry-level practical workflow", text: "Every module is connected with real company work, design checks, reports and interview explanation." },
    { title: "Portfolio-first learning", text: "Students build project proof instead of only watching software commands." },
    { title: "Placement-focused mentoring", text: "Resume, portfolio, mock interview and job-sharing support are connected with the course journey." },
    { title: "Mobile-friendly clarity", text: "Syllabus, projects, demo and batch information are visible clearly before registration." },
  ],
  tutor: { name: "Balkrishna Dhuri", exp: "12+ Years Experience", companies: "Automotive Engineering Expert", initial: "B" },
  outcomes: [
    "Understand plastic part feasibility from injection mould design point of view",
    "Create tooling direction, parting line, parting surface and core-cavity strategy",
    "Plan runner, gate, cooling, venting, ejection and mould-base layout professionally",
    "Handle slider, lifter, shut-off and undercut-related tooling decisions",
    "Read mould flow feedback and connect defects with design corrections",
    "Prepare mould design documentation, BOM and toolroom-style review outputs"
  ],
  includes: [
    { icon: "📹", label: "85-session roadmap", sub: "Live sessions + lifetime recordings" },
    { icon: "🏭", label: "10 portfolio projects", sub: "Industry workflow and interview explanation" },
    { icon: "📊", label: "Project documentation", sub: "Reports, review points and portfolio proof" },
    { icon: "💼", label: "Placement support", sub: "Resume, portfolio and mock interview prep" },
    { icon: "❓", label: "Doubt support", sub: "Project correction and guidance" },
    { icon: "♾", label: "Lifetime access", sub: "Recordings for revision anytime" }
  ],
  syllabusSessions: [
    { no: 1, title: "Injection mould design industry overview", trainer: "Mould Design", category: "Fundamentals" },
    { no: 2, title: "Plastic materials, shrinkage and processing behavior", trainer: "Mould Design", category: "Fundamentals" },
    { no: 3, title: "Injection moulding cycle and machine basics", trainer: "Mould Design", category: "Fundamentals" },
    { no: 4, title: "Mould components and terminology", trainer: "Mould Design", category: "Fundamentals" },
    { no: 5, title: "Plastic part review from tooling point of view", trainer: "Mould Design", category: "Fundamentals" },
    { no: 6, title: "Wall thickness, ribs, bosses and draft review", trainer: "Mould Design", category: "Fundamentals" },
    { no: 7, title: "Common defects: sink, warpage, weld line and flow mark", trainer: "Mould Design", category: "Fundamentals" },
    { no: 8, title: "Tooling direction selection methodology", trainer: "Mould Design", category: "CAD Workflow" },
    { no: 9, title: "Draft analysis and manufacturability validation", trainer: "Mould Design", category: "CAD Workflow" },
    { no: 10, title: "Parting line identification", trainer: "Mould Design", category: "CAD Workflow" },
    { no: 11, title: "Parting surface creation strategy", trainer: "Mould Design", category: "CAD Workflow" },
    { no: 12, title: "Core, cavity and insert planning", trainer: "Mould Design", category: "CAD Workflow" },
    { no: 13, title: "Shut-off surface and sealing area logic", trainer: "Mould Design", category: "CAD Workflow" },
    { no: 14, title: "Undercut identification and solution strategy", trainer: "Mould Design", category: "CAD Workflow" },
    { no: 15, title: "Slider decision and motion direction", trainer: "Mould Design", category: "CAD Workflow" },
    { no: 16, title: "Lifter decision and internal undercut solution", trainer: "Mould Design", category: "Design Rules" },
    { no: 17, title: "Mould base selection and standard plates", trainer: "Mould Design", category: "Design Rules" },
    { no: 18, title: "Cavity layout and single cavity mould planning", trainer: "Mould Design", category: "Design Rules" },
    { no: 19, title: "Multi-cavity and family mould basics", trainer: "Mould Design", category: "Design Rules" },
    { no: 20, title: "Sprue, runner and gate design basics", trainer: "Mould Design", category: "Design Rules" },
    { no: 21, title: "Gate type selection and gate location logic", trainer: "Mould Design", category: "Design Rules" },
    { no: 22, title: "Hot runner and cold runner comparison", trainer: "Mould Design", category: "Design Rules" },
    { no: 23, title: "Cooling channel design fundamentals", trainer: "Mould Design", category: "Design Rules" },
    { no: 24, title: "Baffle, bubbler and conformal cooling overview", trainer: "Mould Design", category: "Manufacturing" },
    { no: 25, title: "Venting strategy and air trap prevention", trainer: "Mould Design", category: "Manufacturing" },
    { no: 26, title: "Ejector pin layout and ejection force basics", trainer: "Mould Design", category: "Manufacturing" },
    { no: 27, title: "Ejector plate, return pin and support pillar logic", trainer: "Mould Design", category: "Manufacturing" },
    { no: 28, title: "Wear plates, guide pins and locking systems", trainer: "Mould Design", category: "Manufacturing" },
    { no: 29, title: "Slider mechanism detailing and locking angle", trainer: "Mould Design", category: "Manufacturing" },
    { no: 30, title: "Lifter mechanism detailing and stroke check", trainer: "Mould Design", category: "Manufacturing" },
    { no: 31, title: "Insert design and replacement strategy", trainer: "Mould Design", category: "Manufacturing" },
    { no: 32, title: "Mould flow report reading basics", trainer: "Mould Design", category: "Validation" },
    { no: 33, title: "Design changes from mould flow feedback", trainer: "Mould Design", category: "Validation" },
    { no: 34, title: "Toolroom feedback and correction workflow", trainer: "Mould Design", category: "Validation" },
    { no: 35, title: "2D mould drawing basics and section views", trainer: "Mould Design", category: "Validation" },
    { no: 36, title: "BOM preparation and standard item list", trainer: "Mould Design", category: "Validation" },
    { no: 37, title: "DFM checklist and design review format", trainer: "Mould Design", category: "Validation" },
    { no: 38, title: "Cost, cycle time and manufacturability thinking", trainer: "Mould Design", category: "Validation" },
    { no: 39, title: "Production trial issues and design correction", trainer: "Mould Design", category: "Validation" },
    { no: 40, title: "Door trim mould strategy workflow", trainer: "Mould Design", category: "Documentation" },
    { no: 41, title: "Cup holder core-cavity workflow", trainer: "Mould Design", category: "Documentation" },
    { no: 42, title: "Bumper bracket tooling workflow", trainer: "Mould Design", category: "Documentation" },
    { no: 43, title: "Toolroom-style review presentation", trainer: "Mould Design", category: "Documentation" },
    { no: 44, title: "Mould design interview preparation", trainer: "Mould Design", category: "Documentation" },
    { no: 45, title: "Final mould design mock review", trainer: "Mould Design", category: "Documentation" },
    { no: 46, title: "Portfolio documentation and screenshots", trainer: "Mould Design", category: "Documentation" },
    { no: 47, title: "Resume points for tooling engineer profile", trainer: "Mould Design", category: "Documentation" },
    { no: 48, title: "Supplier/OEM interview discussion practice", trainer: "Mould Design", category: "Interview" },
    { no: 49, title: "Final project correction and feedback", trainer: "Mould Design", category: "Interview" },
    { no: 50, title: "Career roadmap for mould design engineer", trainer: "Mould Design", category: "Interview" }
  ],
  projectLibrary: ["Switch Bezel Mould", "Fuse Box Cover Mould", "Door Trim Mould Strategy", "Cup Holder Mould Layout", "B-Pillar Trim Mould", "Console Trim Mould", "Front Bumper Tooling", "Runner and Gate Design", "Cooling Channel Layout", "Final Production Tool"],
  portfolioProjects: [
    {
      no: 1,
      title: "Switch Bezel Mould",
      area: "Core-Cavity",
      desc: "Tooling direction, parting line and core-cavity strategy for bezel component.",
      frontImage: "/images/projects/mould-switch-bezel-cad.svg",
      backImage: "/images/projects/mould-switch-bezel-ref.svg",
    },
    {
      no: 2,
      title: "Fuse Box Cover Mould",
      area: "Core-Cavity",
      desc: "Draft review, shrinkage, inserts and ejection planning for cover part.",
      frontImage: "/images/projects/mould-fuse-box-cad.svg",
      backImage: "/images/projects/mould-fuse-box-ref.svg",
    },
    {
      no: 3,
      title: "Door Trim Mould Strategy",
      area: "Automotive Trim",
      desc: "Large plastic trim tooling strategy, sliders and mould feasibility review.",
      frontImage: "/images/projects/mould-door-trim-cad.svg",
      backImage: "/images/projects/mould-door-trim-ref.svg",
    },
    {
      no: 4,
      title: "Cup Holder Mould Layout",
      area: "Mould Layout",
      desc: "Core-cavity, runner-gate and cooling layout for cup holder component.",
      frontImage: "/images/projects/mould-cup-holder-cad.svg",
      backImage: "/images/projects/mould-cup-holder-ref.svg",
    },
    {
      no: 5,
      title: "B-Pillar Trim Mould",
      area: "Automotive Trim",
      desc: "Undercut identification, slider/lifter decision and ejection planning.",
      frontImage: "/images/projects/mould-bpillar-cad.svg",
      backImage: "/images/projects/mould-bpillar-ref.svg",
    },
    {
      no: 6,
      title: "Console Trim Mould",
      area: "Automotive Interior",
      desc: "Parting strategy, shut-off surfaces and cooling layout for console part.",
      frontImage: "/images/projects/mould-console-cad.svg",
      backImage: "/images/projects/mould-console-ref.svg",
    },
    {
      no: 7,
      title: "Front Bumper Tooling",
      area: "Exterior Plastic",
      desc: "Large part tooling direction, slider strategy and DFM review.",
      frontImage: "/images/projects/mould-front-bumper-cad.svg",
      backImage: "/images/projects/mould-front-bumper-ref.svg",
    },
    {
      no: 8,
      title: "Runner and Gate Design",
      area: "Feed System",
      desc: "Gate type selection, runner sizing and filling logic project.",
      frontImage: "/images/projects/mould-runner-gate-cad.svg",
      backImage: "/images/projects/mould-runner-gate-ref.svg",
    },
    {
      no: 9,
      title: "Cooling Channel Layout",
      area: "Cooling System",
      desc: "Cooling design, cycle time thinking and hot spot prevention.",
      frontImage: "/images/projects/mould-cooling-cad.svg",
      backImage: "/images/projects/mould-cooling-ref.svg",
    },
    {
      no: 10,
      title: "Final Production Tool",
      area: "Portfolio Tool",
      desc: "Complete mould design documentation, BOM and toolroom-style review.",
      frontImage: "/images/projects/mould-final-tool-cad.svg",
      backImage: "/images/projects/mould-final-tool-ref.svg",
    }
  ],
  courseFaqs: [
    { q: "Do I need prior experience?", a: "No. The course starts from fundamentals and builds toward practical industry-level projects." },
    { q: "Are sessions live or recorded?", a: "Sessions are live on Zoom and recordings are available for lifetime revision." },
    { q: "Will I build portfolio projects?", a: "Yes. The course includes structured projects that students can explain in interviews." },
    { q: "Will this help in interviews?", a: "Yes. Topics are mapped to real workflow, design decisions, reports and interview questions." },
    { q: "Can freshers join?", a: "Yes. Diploma and BE mechanical freshers can join if they are serious about design/CAE/tooling career." },
    { q: "Is placement support included?", a: "Yes. Resume, portfolio, mock interview and job-sharing support are included." }
  ],
  placements: ["Tata Technologies", "Tata Motors", "Mahindra & Mahindra", "Maruti Suzuki", "Hyundai Motors", "Mercedes-Benz R&D", "BMW Group India", "Volkswagen Group", "Skoda Auto Volkswagen", "Stellantis", "Renault Nissan", "Ashok Leyland", "Magna", "Forvia", "Motherson", "Bosch", "Continental", "ZF", "Valeo", "Aptiv", "Denso", "Schaeffler", "Lear Corporation", "Adient", "Visteon", "Capgemini Engineering", "L&T Technology Services", "KPIT", "Tata Elxsi", "HCLTech", "Wipro", "Tech Mahindra", "Quest Global", "Segula Technologies", "EDAG", "Neilsoft", "Caresoft Global", "Hinduja Tech", "Bajaj Auto", "TVS Motor", "Hero MotoCorp", "Ather Energy", "Ola Electric", "Uno Minda", "Varroc", "Lumax", "Faurecia", "Plastic Omnium", "Yanfeng", "Force Motors"],
};

export default function MouldDesignPage() {
  return <CoursePage course={COURSE} />;
}
