import CoursePage from "./CoursePage.jsx";

const TRAINER = "Mr. Balkrishna Dhuri";

const mainTopics = [
  ["01", "CATIA SURFACING", "Surfacing Training"],
  ["02", "CATIA SURFACING", "Surfacing Training"],
  ["03", "CATIA SURFACING", "Surfacing Training"],
  ["04", "CATIA SURFACING", "Surfacing Training"],
  ["05", "CATIA SURFACING", "Surfacing Training"],
  ["06", "Automotive Development Process", "Theory"],
  ["07", "Benchmarking & Plastic Product Design", "Theory"],
  ["08", "Injection Mould & Draft Analysis", "Theory + Design"],
  ["09", "Tooling Direction Methods", "Theory + Design"],
  ["10", "Class A Surface Analysis", "Theory + Design"],
  ["11", "Tree Structure & Close Body", "Design"],
  ["12", "Map Pocket Close Body", "Design"],
  ["13", "Mastersection Based Close Body", "Design"],
  ["14", "Seat Recliner Cover", "Design"],
  ["15", "Fuse Box Cover", "Design"],
  ["16", "Front Bumper Close Body", "Design"],
  ["17", "Front Bumper – Part 2", "Design"],
  ["18", "Slider, Lifter & Undercuts", "Theory"],
  ["19", "B-Side Features Introduction", "Theory"],
  ["20", "Snap Design", "Theory + Design"],
  ["21", "Locator Design", "Theory + Design"],
  ["22", "Dog House Design", "Theory + Design"],
  ["23", "Clip Tower Design", "Theory + Design"],
  ["24", "Weld & Screw Boss", "Theory + Design"],
  ["25", "Ribs Design", "Theory + Design"],
  ["26", "Powercopy", "Design"],
  ["27", "RPS & Locating Strategy", "Theory + Design"],
  ["28", "Gap & Flush", "Design"],
  ["29", "Mastersection Exercise 01", "Design Exercise"],
  ["30", "Mastersection EX. 02", "Design Exercise"],
  ["31", "Mastersection EX. 03", "Design Exercise"],
  ["32", "Mastersection EX. 04", "Design Exercise"],
  ["33", "Mastersection EX. 05", "Design Exercise"],
  ["34", "Mastersection EX. 06", "Design Exercise"],
  ["35", "Mastersection Variable Thickness", "Design Exercise"],
  ["36", "Remastering Boolean", "Design Exercise"],
  ["37", "Remastering Surfacing", "Design Exercise"],
  ["38", "Style Replacement Methods", "Design"],
  ["39", "GD and T", "Theory"],
  ["40", "Plastic Defects", "Theory"],
  ["41", "Plastic Materials", "Theory"],
  ["42", "DMU Analysis and Report Creation", "Analysis"],
  ["43", "Resume Building and Mock Interview", "Career"],
  ["44", "Mock Interview Session 01", "Career"],
  ["45", "Mock Interview Session 02", "Career"],
  ["46", "Shut off and Graining", "Theory"],
  ["47", "2D Drawing creation", "Design"],
  ["48", "Features Remastering", "Design"],
  ["49", "Mold Flow analysis Report reading", "Theory"],
  ["50", "Toolroom mold design review", "Theory"],
];

const practiceTopics = [
  ["51", "Advanced Project Orientation & File Setup", "Project Practice"],
  ["52", "Cup Holder CATIA Solution Workflow", "CATIA Project"],
  ["53", "B Pillar Upper CATIA Solution Workflow", "CATIA Project"],
  ["54", "Seat Recliner Cover NX Solution Workflow", "NX Project"],
  ["55", "Armrest Project CATIA Solution Workflow", "CATIA Project"],
  ["56", "B Pillar Upper NX Solution Workflow", "NX Project"],
  ["57", "Map Pocket Design CATIA Solution Workflow", "CATIA Project"],
  ["58", "Map Pocket Design NX Solution Workflow", "NX Project"],
  ["59", "Cup Holder NX Solution Workflow", "NX Project"],
  ["60", "Fuse Box Cover CATIA Solution Workflow", "CATIA Project"],
  ["61", "Mastersection Practice NX Workflow", "NX Project"],
  ["62", "Project Tree Structure & Naming Standards", "CAD Standards"],
  ["63", "Input Data Study: Class-A, Master Section & Packaging", "Design Method"],
  ["64", "Tooling Direction & Draft Strategy for Practice Projects", "DFM"],
  ["65", "Close Body Quality Check & Surface Continuity", "Quality Check"],
  ["66", "B-Side Feature Placement Review", "Design Review"],
  ["67", "Snap, Locator, Dog House & Rib Validation", "Design Review"],
  ["68", "Assembly Clearance, Gap & Flush Check", "DMU"],
  ["69", "CATIA to NX Method Comparison", "Tool Comparison"],
  ["70", "Project Error Debugging & Rework Methods", "CAD Debugging"],
  ["71", "Drawing, Screenshots & Report Preparation", "Documentation"],
  ["72", "DFM Checklist for Plastic Trim Projects", "DFM"],
  ["73", "Mould Feasibility Review for Project Parts", "Mould Review"],
  ["74", "Portfolio Sheet Creation for Each Project", "Portfolio"],
  ["75", "Interview Explanation: Project 01 to 03", "Interview Prep"],
  ["76", "Interview Explanation: Project 04 to 06", "Interview Prep"],
  ["77", "Interview Explanation: Project 07 to 10", "Interview Prep"],
  ["78", "Mock Technical Review With Project Questions", "Mock Interview"],
  ["79", "Resume Project Description Writing", "Career"],
  ["80", "Final Portfolio Review & Job Readiness Checklist", "Career"],
];

const SYLLABUS_SESSIONS = mainTopics.map(([no, title, category]) => ({ no, title, category, trainer: TRAINER }));
const PROJECT_PRACTICE_SESSIONS = practiceTopics.map(([no, title, category]) => ({ no, title, category, trainer: TRAINER }));

const PORTFOLIO_PROJECTS = [
  { no: "01", title: "Seat Recliner Cover", short: "Seat side trim cover", frontImage: "images/Projects/p01-cad.png", backImage: "images/Projects/p01-car.png", area: "Seat Trims", tag: "Seat Trims", desc: "OEM CAD + real position reference." },
  { no: "02", title: "Fuse Box Cover", short: "Dashboard Trim", frontImage: "images/Projects/p02-cad.png", backImage: "images/Projects/p02-car.png", area: "IP / Dashboard", tag: "Dashboard", desc: "Dashboard-side packaging and cover design workflow." },
  { no: "03", title: "Cup Holder", short: "Console Trim", frontImage: "images/Projects/p03-cad.png", backImage: "images/Projects/p03-car.png", area: "Center Console", tag: "Console", desc: "Interior utility part with styling, draft and mounting logic." },
  { no: "04", title: "Central FACIA", short: "Dashboard Trim", frontImage: "images/Projects/p04-cad.png", backImage: "images/Projects/p04-car.png", area: "IP / Dashboard", tag: "Dashboard", desc: "Instrument panel trim design with visible styling constraints." },
  { no: "05", title: "Map Pocket", short: "Door storage pocket", frontImage: "images/Projects/p05-cad.png", backImage: "images/Projects/p05-car.png", area: "Door Trims", tag: "Door Trims", desc: "Door trim storage pocket with manufacturable B-side features." },
  { no: "06", title: "Armrest Module", short: "Door armrest zone", frontImage: "images/Projects/p06-cad.png", backImage: "images/Projects/p06-car.png", area: "Door Trims", tag: "Door Trims", desc: "Armrest zone project with locator, support and assembly thinking." },
  { no: "07", title: "B-Pillar Upper Trim", short: "Pillar trim", frontImage: "images/Projects/p07-cad.png", backImage: "images/Projects/p07-car.png", area: "Pillar Trims", tag: "Pillar Trims", desc: "Pillar cover with class-A to close-body and mounting strategy." },
  { no: "08", title: "Tailgate Inner Trim", short: "Tailgate inner panel", frontImage: "images/Projects/p08-cad.png", backImage: "images/Projects/p08-car.png", area: "Tailgate Trims", tag: "Tailgate", desc: "Tailgate trim project with packaging and tooling constraints." },
  { no: "09", title: "Front Bumper", short: "Bumper Trim", frontImage: "images/Projects/p09-cad.png", backImage: "images/Projects/p09-car.png", area: "Front Bumper", tag: "Bumper", desc: "Exterior plastic component with close body and mould feasibility." },
];

const COURSE_FAQS = [
  { q: "Am I eligible for this program?", a: ["Mechanical Engineering BE / Diploma freshers", "Students or professionals with career gaps", "Engineers from Production, Quality, Manufacturing", "Professionals switching into design domain", "Mechanical students who want early job readiness"] },
  { q: "Do I need CAD basics?", a: ["No prior CAD knowledge required.", "Foundation concepts explained first", "Step-by-step practical training", "Assignments and practice included", "Mentor guidance throughout learning"] },
  { q: "What if I miss a class?", a: ["All sessions will be recorded", "You get recording access in just 5-10 minutes after live session", "While practicing, doubts will be resolved by tutor"] },
  { q: "What software will I learn?", a: ["CATIA V5 – 7 Projects", "Siemens NX – 5 Projects", "Real automotive design workflow", "Industry-relevant project portfolio"] },
  { q: "How does job assistance work?", a: ["250+ Genuine HR contacts", "Portfolio, Resume building, online/offline Mock Interviews special session", "Genuine unlimited opportunities will be shared until you get a deserving job"] },
  { q: "Is EMI available?", a: ["Yes, EMI options are available", "Flexible payment options with no extra processing fees", "Two EMI can be paid"] },
  { q: "How do I enroll?", a: ["Connect via WhatsApp", "Discuss your background", "Understand course details", "Confirm registration", "Get onboarding instructions"] },
];

const COURSE = {
  slug: "plastic-product-design",
  name: "Automotive Plastic Product Design",
  tagline: "From Zero to Industry-Ready in 4 Months",
  eyebrow: "Automotive Plastic Trims Career Program",
  badge: "🏆 Most Popular",
  badgeBg: "#FFEB3A",
  badgeColor: "#1C1C1C",
  price: 18000,
  regularPrice: 20999,
  regularOfferPrice: 20999,
  slashPrice: 24000,
  rating: "4.9",
  reviews: "312",
  enrolled: "312+",
  duration: "4 Months",
  sessions: "80",
  projectCount: "19+",
  roadmapLabel: "100 days training roadmap",
  roadmapCopy: "Core syllabus plus CATIA/NX project practice for automotive plastic product design.",
  heroCopy: "OEM-level automotive plastic product design training with CATIA + NX, real projects, portfolio support and placement-focused interview preparation.",
  tools: ["CATIA V5", "UG NX", "GSD Surfacing", "Draft Analysis", "Plastic Trims", "GD&T"],
  packageRange: "₹3.5–16 LPA",
  trustYears: "7+",
  partnerLine: "Digital CAD Training is partner and authorized by CADPOINT for professional CAD training direction.",
  trustCopy: "Students see the complete syllabus, projects, career path and registration value clearly before joining. The program is positioned around CADPOINT authorization, PAN India MNC/OEM/Tier-1 hiring exposure and placement-focused mentoring.",
  packageNote: "Package depends on skill, location, interview performance and company requirement. We guide students for fresher to junior design engineer level roles across PAN India automotive hiring networks.",
  trustHighlights: ["CADPOINT Authorized Partner", "PAN India MNC/OEM hiring exposure", "7+ years trust connection", "Package guidance ₹3.5–16 LPA"],
  trustProofs: [
    { title: "CADPOINT authorized partner", text: "Adds credibility that the training brand is connected with a professional CAD education ecosystem." },
    { title: "PAN India hiring exposure", text: "Students are prepared for MNC, OEM and Tier-1 supplier interviews across multiple automotive locations." },
    { title: "2–3 years experience-level learning", text: "Projects, reports, design decisions and interview preparation are structured beyond basic tool commands." },
    { title: "Placement-focused mentoring", text: "Resume, portfolio, mock interview and job-sharing support are connected with the course journey." },
  ],
  tutor: { name: "Balkrishna Dhuri", exp: "12 Years Experience", companies: "Automotive Product Design Expert", initial: "B" },
  whoCanJoin: ["BE / Diploma freshers", "Production engineers", "Quality engineers", "CAD beginners", "Career gap students"],
  outcomes: [
    "Understand automotive plastic trims design workflow",
    "Create close body from Class-A surfaces",
    "Design B-side features like snap, locator, dog house and ribs",
    "Check tooling direction, draft, undercut and mould feasibility",
    "Build portfolio projects with real vehicle context",
    "Prepare for automotive product design interviews",
  ],
  includes: [
    { icon: "📹", label: "Live + Recorded Sessions", sub: "Session recording access after live class" },
    { icon: "🏭", label: "Real Automotive Projects", sub: "CAD model + in-car position understanding" },
    { icon: "🧰", label: "CATIA + NX Exposure", sub: "Industry-relevant plastic trims workflow" },
    { icon: "📐", label: "Tooling & Mould Logic", sub: "Draft, undercut, slider, lifter, tooling direction" },
    { icon: "💼", label: "Placement Support", sub: "Resume, portfolio and interview preparation" },
    { icon: "❓", label: "Doubt Support", sub: "Ask practical doubts while practicing" },
  ],
  offerInfoItems: [
    { title: "Learn in both CATIA V5 + UGNX software", text: "45 syllabus topics in CATIA V5 + 10 projects in CATIA + 5 projects in NX." },
    { title: "Live + lifetime recording", text: "100% live Zoom sessions alternative days + recording access for lifetime revision." },
  ],
  syllabusSessions: SYLLABUS_SESSIONS,
  projectPracticeSessions: PROJECT_PRACTICE_SESSIONS,
  portfolioProjects: PORTFOLIO_PROJECTS,
  projectLibrary: [],
  syllabusPdf: "downloads/plastic-product-design-detailed-syllabus.pdf",
  courseFaqs: COURSE_FAQS,
  placements: ["TATA Motors", "Mahindra", "SEGULA Technologies", "TATA ELXSI", "Capgemini", "Faurecia", "HCL", "Wipro", "Force Motors", "Motherson", "Bajaj", "Bright Brothers"],
};

export default function PlasticProductDesignPage() {
  return <CoursePage course={COURSE} />;
}
