import CoursePage from "./CoursePage.jsx";

const TRAINER = "Mr. Balkrishna Dhuri";

const SYLLABUS_SESSIONS = [
  { no: "01", title: "CATIA SURFACING", category: "Surfacing Training", trainer: TRAINER },
  { no: "02", title: "CATIA SURFACING", category: "Surfacing Training", trainer: TRAINER },
  { no: "03", title: "CATIA SURFACING", category: "Surfacing Training", trainer: TRAINER },
  { no: "04", title: "CATIA SURFACING", category: "Surfacing Training", trainer: TRAINER },
  { no: "05", title: "CATIA SURFACING", category: "Surfacing Training", trainer: TRAINER },
  { no: "06", title: "Automotive Development Process", category: "Theory", trainer: TRAINER },
  { no: "07", title: "Benchmarking & Plastic Product Design", category: "Theory", trainer: TRAINER },
  { no: "08", title: "Injection Mould & Draft Analysis", category: "Theory + Design", trainer: TRAINER },
  { no: "09", title: "Tooling Direction Methods", category: "Theory + Design", trainer: TRAINER },
  { no: "10", title: "Class A Surface Analysis", category: "Theory + Design", trainer: TRAINER },
  { no: "11", title: "Tree Structure & Close Body", category: "Design", trainer: TRAINER },
  { no: "12", title: "Map Pocket Close Body", category: "Design", trainer: TRAINER },
  { no: "13", title: "Mastersection Based Close Body", category: "Design", trainer: TRAINER },
  { no: "14", title: "Seat Recliner Cover", category: "Design", trainer: TRAINER },
  { no: "15", title: "Fuse Box Cover", category: "Design", trainer: TRAINER },
  { no: "16", title: "Front Bumper Close Body", category: "Design", trainer: TRAINER },
  { no: "17", title: "Front Bumper – Part 2", category: "Design", trainer: TRAINER },
  { no: "18", title: "Slider, Lifter & Undercuts", category: "Theory", trainer: TRAINER },
  { no: "19", title: "B-Side Features Introduction", category: "Theory", trainer: TRAINER },
  { no: "20", title: "Snap Design", category: "Theory + Design", trainer: TRAINER },
  { no: "21", title: "Locator Design", category: "Theory + Design", trainer: TRAINER },
  { no: "22", title: "Dog House Design", category: "Theory + Design", trainer: TRAINER },
  { no: "23", title: "Clip Tower Design", category: "Theory + Design", trainer: TRAINER },
  { no: "24", title: "Weld & Screw Boss", category: "Theory + Design", trainer: TRAINER },
  { no: "25", title: "Ribs Design", category: "Theory + Design", trainer: TRAINER },
  { no: "26", title: "Powercopy", category: "Design", trainer: TRAINER },
  { no: "27", title: "RPS & Locating Strategy", category: "Theory + Design", trainer: TRAINER },
  { no: "28", title: "Gap & Flush", category: "Design", trainer: TRAINER },
  { no: "29", title: "Mastersection Exercise 01", category: "Design Exercise", trainer: TRAINER },
  { no: "30", title: "Mastersection EX. 02", category: "Design Exercise", trainer: TRAINER },
  { no: "31", title: "Mastersection EX. 03", category: "Design Exercise", trainer: TRAINER },
  { no: "32", title: "Mastersection EX. 04", category: "Design Exercise", trainer: TRAINER },
  { no: "33", title: "Mastersection EX. 05", category: "Design Exercise", trainer: TRAINER },
  { no: "34", title: "Mastersection EX. 06", category: "Design Exercise", trainer: TRAINER },
  { no: "35", title: "Mastersection Variable Thickness", category: "Design Exercise", trainer: TRAINER },
  { no: "36", title: "Remastering Boolean", category: "Design Exercise", trainer: TRAINER },
  { no: "37", title: "Remastering Surfacing", category: "Design Exercise", trainer: TRAINER },
  { no: "38", title: "Style Replacement Methods", category: "Design", trainer: TRAINER },
  { no: "39", title: "GD and T", category: "Theory", trainer: TRAINER },
  { no: "40", title: "Plastic Defects", category: "Theory", trainer: TRAINER },
  { no: "41", title: "Plastic Materials", category: "Theory", trainer: TRAINER },
  { no: "42", title: "DMU Analysis and Report Creation", category: "Analysis", trainer: TRAINER },
  { no: "43", title: "Resume Building and Mock Interview", category: "Career", trainer: TRAINER },
  { no: "44", title: "Mock Interview Session 01", category: "Career", trainer: TRAINER },
  { no: "45", title: "Mock Interview Session 02", category: "Career", trainer: TRAINER },
  { no: "46", title: "Shut off and Graining", category: "Theory", trainer: TRAINER },
  { no: "47", title: "2D Drawing creation", category: "Design", trainer: TRAINER },
  { no: "48", title: "Features Remastering", category: "Design", trainer: TRAINER },
  { no: "49", title: "Mold Flow analysis Report reading", category: "Theory", trainer: TRAINER },
  { no: "50", title: "Toolroom mold design review", category: "Theory", trainer: TRAINER },
  { no: "51", title: "Advanced Project Orientation & File Setup", category: "Project Practice", trainer: TRAINER },
  { no: "52", title: "Cup Holder CATIA Solution Workflow", category: "CATIA Project", trainer: TRAINER },
  { no: "53", title: "B Pillar Upper CATIA Solution Workflow", category: "CATIA Project", trainer: TRAINER },
  { no: "54", title: "Seat Recliner Cover NX Solution Workflow", category: "NX Project", trainer: TRAINER },
  { no: "55", title: "Armrest Project CATIA Solution Workflow", category: "CATIA Project", trainer: TRAINER },
  { no: "56", title: "B Pillar Upper NX Solution Workflow", category: "NX Project", trainer: TRAINER },
  { no: "57", title: "Map Pocket Design CATIA Solution Workflow", category: "CATIA Project", trainer: TRAINER },
  { no: "58", title: "Map Pocket Design NX Solution Workflow", category: "NX Project", trainer: TRAINER },
  { no: "59", title: "Cup Holder NX Solution Workflow", category: "NX Project", trainer: TRAINER },
  { no: "60", title: "Fuse Box Cover CATIA Solution Workflow", category: "CATIA Project", trainer: TRAINER },
  { no: "61", title: "Mastersection Practice NX Workflow", category: "NX Project", trainer: TRAINER },
  { no: "62", title: "Project Tree Structure & Naming Standards", category: "CAD Standards", trainer: TRAINER },
  { no: "63", title: "Input Data Study: Class-A, Master Section & Packaging", category: "Design Method", trainer: TRAINER },
  { no: "64", title: "Tooling Direction & Draft Strategy for Practice Projects", category: "DFM", trainer: TRAINER },
  { no: "65", title: "Close Body Quality Check & Surface Continuity", category: "Quality Check", trainer: TRAINER },
  { no: "66", title: "B-Side Feature Placement Review", category: "Design Review", trainer: TRAINER },
  { no: "67", title: "Snap, Locator, Dog House & Rib Validation", category: "Design Review", trainer: TRAINER },
  { no: "68", title: "Assembly Clearance, Gap & Flush Check", category: "DMU", trainer: TRAINER },
  { no: "69", title: "CATIA to NX Method Comparison", category: "Tool Comparison", trainer: TRAINER },
  { no: "70", title: "Project Error Debugging & Rework Methods", category: "CAD Debugging", trainer: TRAINER },
  { no: "71", title: "Drawing, Screenshots & Report Preparation", category: "Documentation", trainer: TRAINER },
  { no: "72", title: "DFM Checklist for Plastic Trim Projects", category: "DFM", trainer: TRAINER },
  { no: "73", title: "Mould Feasibility Review for Project Parts", category: "Mould Review", trainer: TRAINER },
  { no: "74", title: "Portfolio Sheet Creation for Each Project", category: "Portfolio", trainer: TRAINER },
  { no: "75", title: "Interview Explanation: Project 01 to 03", category: "Interview Prep", trainer: TRAINER },
  { no: "76", title: "Interview Explanation: Project 04 to 06", category: "Interview Prep", trainer: TRAINER },
  { no: "77", title: "Interview Explanation: Project 07 to 10", category: "Interview Prep", trainer: TRAINER },
  { no: "78", title: "Mock Technical Review With Project Questions", category: "Mock Interview", trainer: TRAINER },
  { no: "79", title: "Resume Project Description Writing", category: "Career", trainer: TRAINER },
  { no: "80", title: "Final Portfolio Review & Job Readiness Checklist", category: "Career", trainer: TRAINER },
];

const PORTFOLIO_PROJECTS = [
  { no: "01", title: "Seat Recliner Cover", short: "Seat side trim cover", frontImage: "images/Projects/p01-cad.png", backImage: "images/Projects/p01-car.png", area: "Seat Trims", tag: "Seat Trims", desc: "OEM CAD + real position reference." },
  { no: "02", title: "Fuse Box Cover", short: "Dashboard Trim", frontImage: "images/Projects/p02-cad.png", backImage: "images/Projects/p02-car.png", area: "IP / Dashboard", tag: "Dashboard", desc: "Dashboard-side packaging and cover design workflow." },
  { no: "03", title: "Cup Holder", short: "Console Trim", frontImage: "images/Projects/p03-cad.png", backImage: "images/Projects/p03-car.png", area: "Center Console", tag: "Console", desc: "Interior utility part with styling, draft and mounting logic." },
  { no: "04", title: "Central FACIA", short: "Dashboard Trim", frontImage: "images/Projects/p04-cad.png", backImage: "images/Projects/p04-car.png", area: "IP / Dashboard", tag: "Dashboard", desc: "Instrument panel trim design with visible styling constraints." },
  { no: "05", title: "Map Pocket", short: "Door storage pocket", frontImage: "images/Projects/p05-cad.png", backImage: "images/Projects/p05-car.png", area: "Door Trims", tag: "Door Trims", desc: "Door trim storage pocket with manufacturable B-side features." },
  { no: "06", title: "Armrest Module", short: "Door armrest zone", frontImage: "images/Projects/p06-cad.png", backImage: "images/Projects/p06-car.png", area: "Door Trims", tag: "Door Trims", desc: "Armrest zone project with locator, support and assembly thinking." },
  { no: "07", title: "B-Pillar Upper Trim", short: "Pillar trim", frontImage: "images/Projects/p07-cad.png", backImage: "images/Projects/p07-car.png", area: "Pillar Trims", tag: "Pillar Trims", desc: "Pillar cover with class-A to close-body and mounting strategy." },
  { no: "08", title: "Tailgate Inner Trim", short: "Tailgate inner panel", frontImage: "images/Projects/p08-cad.png", backImage: "images/Projects/p08-car.png", area: "Tailgate Trims", tag: "Tailgate", desc: "Tailgate trim project with packaging and tooling constraints." },
  { no: "09", title: "Front Bumper", short: "Bumper Trim", frontImage: "images/Projects/p09-cad.png", backImage: "images/Projects/p09-car.png", area: "Front Bumper", tag: "Bumper", desc: "Exterior plastic component with close body and mould feasibility." },
];


const SOLUTION_PROJECT_LIBRARY = [
  "PROJECT 01 - CUP HOLDER CATIA SOLUTION",
  "PROJECT 02 - B PILLAR UPPER CATIA SOLUTION",
  "PROJECT 03 - SEAT RECLINER COVER NX SOLUTION",
  "PROJECT 04 - ARMREST PROJECT - CATIA SOLUTION",
  "PROJECT 05 - B PILLAR UPPER - NX SOLUTION",
  "PROJECT 06 - MAP POCKET DESIGN CATIA SOLUTION",
  "PROJECT 07 - MAP POCKET DESIGN NX SOLUTION",
  "PROJECT 08 - CUP HOLDER NX SOLUTION",
  "PROJECT 09 - FUSE BOX COVER - CATIA SOLUTION",
  "PROJECT 10 - Mastersection Practice NX",
];

const COURSE_FAQS = [
  { q: "Am I eligible for this program?", a: ["Mechanical Engineering BE / Diploma freshers", "Students or professionals with career gaps", "Engineers from Production, Quality, Manufacturing", "Professionals switching into design domain", "Mechanical students who want early job readiness"] },
  { q: "Do I need CAD basics?", a: ["No prior CAD knowledge required.", "Foundation concepts explained first", "Step-by-step practical training", "Assignments and practice included", "Mentor guidance throughout learning"] },
  { q: "What if I miss a class?", a: ["All sessions will be recorded", "You get recording access in just 5-10 minutes after live session", "While practicing, doubts will be resolved by tutor"] },
  { q: "What software will I learn?", a: ["CATIA V5 – 7 Projects", "Siemens NX – 5 Projects", "Real automotive design workflow", "Industry-relevant project portfolio"] },
  { q: "How does job assistance work?", a: ["250+ Genuine HR contacts", "Portfolio, Resume building, online/offline Mock Interviews special session", "Genuine unlimited opportunities will be shared until you get a deserving job"] },
  { q: "Is EMI available?", a: ["Yes, EMI options are available", "Flexible payment options with no extra processing fees", "Two EMI can be paid"] },
  { q: "How do I enroll?", a: ["Connect via WhatsApp", "Discuss your background", "Understand course details", "Confirm registration", "Get onboarding instructions"] },
];

const COURSE = {
  slug: "plastic-product-design",
  name: "Automotive Plastic Product Design",
  tagline: "From Zero to Industry-Ready in 4 Months",
  eyebrow: "Automotive Plastic Trims Career Program",
  badge: "🏆 Most Popular",
  badgeBg: "#FFEB3A",
  badgeColor: "#1C1C1C",
  price: 18000,
  slashPrice: 24000,
  rating: "4.9",
  reviews: "312",
  enrolled: "312+",
  duration: "4 Months",
  sessions: "80",
  projectCount: "19+",
  heroCopy: "OEM-level automotive plastic product design training with CATIA + NX, real projects, portfolio support and placement-focused interview preparation.",
  tools: ["CATIA V5", "UG NX", "GSD Surfacing", "Draft Analysis", "Plastic Trims", "GD&T"],
  packageRange: "₹3.5–8 LPA",
  trustYears: "7+",
  partnerLine: "Digital CAD Training is partner and authorized by CADPOINT for professional CAD training direction.",
  trustCopy: "Students see the complete syllabus, projects, career path and registration value clearly before joining. The program is positioned around CADPOINT authorization, PAN India MNC/OEM/Tier-1 hiring exposure and placement-focused mentoring.",
  packageNote: "Package depends on skill, location, interview performance and company requirement. We guide students for fresher to junior design engineer level roles across PAN India automotive hiring networks.",
  trustHighlights: ["CADPOINT Authorized Partner", "PAN India MNC/OEM hiring exposure", "7+ years trust connection", "Package guidance ₹3.5–8 LPA"],
  trustProofs: [
    { title: "CADPOINT authorized partner", text: "Adds credibility that the training brand is connected with a professional CAD education ecosystem." },
    { title: "PAN India hiring exposure", text: "Students are prepared for MNC, OEM and Tier-1 supplier interviews across multiple automotive locations." },
    { title: "2–3 years experience-level learning", text: "Projects, reports, design decisions and interview preparation are structured beyond basic tool commands." },
    { title: "Placement-focused mentoring", text: "Resume, portfolio, mock interview and job-sharing support are connected with the course journey." },
  ],
  tutor: { name: "Balkrishna Dhuri", exp: "12 Years Experience", companies: "Automotive Product Design Expert", initial: "B" },
  whoCanJoin: ["BE / Diploma freshers", "Production engineers", "Quality engineers", "CAD beginners", "Career gap students"],
  outcomes: [
    "Understand automotive plastic trims design workflow",
    "Create close body from Class-A surfaces",
    "Design B-side features like snap, locator, dog house and ribs",
    "Check tooling direction, draft, undercut and mould feasibility",
    "Build portfolio projects with real vehicle context",
    "Prepare for automotive product design interviews",
  ],
  includes: [
    { icon: "📹", label: "Live + Recorded Sessions", sub: "Session recording access after live class" },
    { icon: "🏭", label: "Real Automotive Projects", sub: "CAD model + in-car position understanding" },
    { icon: "🧰", label: "CATIA + NX Exposure", sub: "Industry-relevant plastic trims workflow" },
    { icon: "📐", label: "Tooling & Mould Logic", sub: "Draft, undercut, slider, lifter, tooling direction" },
    { icon: "💼", label: "Placement Support", sub: "Resume, portfolio and interview preparation" },
    { icon: "❓", label: "Doubt Support", sub: "Ask practical doubts while practicing" },
  ],
  syllabusSessions: SYLLABUS_SESSIONS,
  portfolioProjects: PORTFOLIO_PROJECTS,
  projectLibrary: SOLUTION_PROJECT_LIBRARY,
  syllabusPdf: "downloads/plastic-product-design-detailed-syllabus.pdf",
  courseFaqs: COURSE_FAQS,
  placements: ["TATA Motors", "Mahindra", "SEGULA Technologies", "TATA ELXSI", "Capgemini", "Faurecia", "HCL", "Wipro", "Force Motors", "Motherson", "Bajaj", "Bright Brothers"],
};

export default function PlasticProductDesignPage() {
  return <CoursePage course={COURSE} />;
}
